#!/bin/sh
# Check golang lint
if [ -f go.mod ] &&command -v golangci-lint >/dev/null; then
  golangci-lint run 1>&2
  if [ $? -ne 0 ]; then
    echo 1>&2 "  (use \"git push --no-verify\" to discard)";
    exit 2;
  fi
fi

exit 0